### ISSUE TITLE
Search and white screen

### ISSUE THREAD

**Issue by princepeace** [croccio/CarTube#26] opened 2021-03-26 21:11 UTC
Doing a second video search after the first one results in a blank, white screen, with no search results. I have to restart AA to get search working again.

**Comment by costa802** [comment] 2021-03-26 21:26
A me no, anche la seconda ricerca funziona!

**Comment by croccio** [comment] 2021-03-26 21:31
probably it could be a connection issue. @princepeace  can you reproduce it
always or sometime?

Il giorno ven 26 mar 2021 alle ore 22:26 costa802 ***@***.***>
ha scritto:

**Comment by princepeace** [comment] 2021-03-26 21:39
Will try again tomorrow, but I am reporting based on tests I did on Thursday and Friday.

**Comment by croccio** [comment] 2021-03-26 21:44
Ok thanks, I'll investigating on it with a slow internet connection. Maybe
it will be the cause.

Il giorno ven 26 mar 2021 alle ore 22:39 princepeace <
***@***.***> ha scritto:

**Comment by princepeace** [comment] 2021-03-26 21:49
I was using 5G, so connection definitely not the issue.

**Comment by croccio** [comment] 2021-03-26 21:53
😮 ok that's not the problem 😁

Il ven 26 mar 2021, 22:49 princepeace ***@***.***> ha scritto:

**Comment by princepeace** [comment] 2021-03-26 21:56
I also use Adguard, I wonder if that is affecting things so I will whitelist Cartube and try again tomorrow.

**Comment by princepeace** [comment] 2021-03-27 15:37
Tried search again a few times today, seemed to work without programmes today. I whitelisted CarTube/CarTube Controller as I suggested I would yesterday, so maybe that was a factor.

**Comment by croccio** [comment] 2021-03-27 15:46
Great :) i'm closing this issue! if u have other problems related to search fell free to reopen this :)

**Closed by croccio** 2021-03-27 15:46 UTC
Labels: bug, car-tube, to-investigate
